### ISSUE TITLE
The result of FeSSSS

### ISSUE THREAD

**Issue by lechchu** [TouqeerAhmad/FeSSSS#1]
Thanks for releasing the source code,I have some questions about the results when I training.

Here is my training script, with 60 features files.
```
python FeatureExtraction_MocoV2.py --arch resnet18 --layer_names layer4 --weights cub200_cec.pth --feature_file_name supervised/session_01/features_auo_train_01.npy --N_feature 512 --split train --session_ID 1 --model_Type_input supervised --special_net cec --ignore_fc
python FeatureExtraction_MocoV2.py --arch resnet18 --layer_names layer4 --weights cub200_cec.pth --feature_file_name supervised/session_01/features_auo_val_central.npy --N_feature 512 --split val --session_ID 1 --model_Type_input supervised --special_net cec --ignore_fc

python FeatureExtraction_MocoV2.py --arch resnet50 --layer_names avgpool --weights mocov2_pretrain.pth.tar --feature_file_name self_supervised/session_01/features_auo_train_01.npy --split train --N_feature 2048 --sessions 5 --model_Type_input self --for_moco
python FeatureExtraction_MocoV2.py --arch resnet50 --layer_names avgpool --weights mocov2_pretrain.pth.tar --feature_file_name self_supervised/session_01/features_auo_val_central.npy --split val --N_feature 2048 --for_moco  --session_ID 1
```
```
python mlpTrain_Concat.py --dataSetInUse CUB --featureBeingUsed concat --NUMBER_OF_FEATURE_FILES 60 --base_epochs 1000 --gnerateData\
--root_path / --dirSelfSupervisedFeatures self_supervised/ --dirSupervisedFeatures supervised/ > terminal_Incremental_Session_CUB.txt
```
And it is the result of the script:
CUB200
77.65, 71.49, 68.54, 65.02, 61.72, 57.81, 56.16, 55.12, 52.54, 51.80, 50.48
The result from paper:
79.60, 73.46, 70.32, 66.38, 63.97, 59.63, 58.19, 57.56, 55.01, 54.31, 52.98

There is a difference of about 2%, the same situation with cifar100
my result:
73.73, 69.57, 65.36, 61.29, 57.93, 54.68, 53.09, 50.14, 47.67
paper result:
75.35, 70.81, 66.70, 62.73, 59.62, 56.45, 54.33, 52.10, 50.23

Did I missing any setting or parameters? 
Thank you!

**Comment by TouqeerAhmad** [comment]
Hello, Thank you for your interest in our work!
Yes, for CUB200 the results you shared from paper's Table1 are based on DeepClusterv2 network, not the MocoV2. The numbers for MocoV2 and other self-supervised models can be found in Table6 in the supplemental. 

https://drive.google.com/file/d/1NMiVTmSzoa8s2isFVhmAqHg8ChZXhQMo/view

Please let me know if you have any other concern. 
One correction to note for Table6 in the supplemental, the SeLa-v2 and Moco-v2 numbers are switched. The ones reported for Moco-v2 are actually for SeLa-v2 and vice versa. These are the numbers you should expect for Mocov2: 

77.44 | 71.68 | 68.48 | 64.56 | 61.86 | 57.85 | 56.52 | 54.89 | 52.59 | 52.63 | 51.43 | 60.9027272727273
